### ISSUE TITLE
Support Querying

### ISSUE THREAD

**Issue by graywolf336** [qeesung/rocketchat-node#24]
Just thought I'd let you know, some of the endpoints support querying. This isn't documented anywhere yet due to a lack of time on my part: https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-api/server/v1/helpers/parseJsonQuery.js

**Comment by graywolf336** [comment]
See here for some documentation: https://github.com/RocketChat/Rocket.Chat/pull/5411

**Comment by qeesung** [comment]
@graywolf336 👍 We will add query support for `*.list` interfaces

**Comment by MatthiasKainer** [comment]
is it okay if I switch to a `.list(settings : { offset, count, query : { sort, fields, query }}, callback)` signature then? I'd process it in a central list mapper so that on future breaking changes no client would have to change anything, only us.

**Comment by graywolf336** [comment]
Why not switch all of your options to the es6 object spread operator? `function channelsList({ offset, count, query: { sort, fields, query }})` that way you can easily add more supported parameters without breaking things.

**Comment by MatthiasKainer** [comment]
we are breaking things now, that's why I asked :laughing: 

With mapping I meant breaking changes in rocket.chat - let's say offset and count would be moved in a page object in a new version, the mapper could handle that change for clients using that library. but I guess that would mean introducing unnecessary complexity while making things harder to find out/debug for the consumer. stupid idea, dropped it :balloon:

**Comment by MatthiasKainer** [comment]
But spread operator is a great idea, thx - will have to test if it works with node5, otherwise maybe we should consider dropping support?

**Comment by graywolf336** [comment]
The pagination items won't change until v2 of the rest api, so if you're developing this for `v1` then it is safe to assume the names will stay exactly the same. So, it shouldn't have any breaking changes for a while. :)

**Comment by MatthiasKainer** [comment]
good to know, thx :)

@qeesung tested it, we will have to drop node5 support for object spread operator. Okay for you? That case I'd remove it from travis and implement a first proposal for channels.list

**Comment by qeesung** [comment]
@MatthiasKainer Cool! It is a good idea to switch to ES6. Should we switch all interfaces to ES6?

**Comment by MatthiasKainer** [comment]
Jop, step by step - also we should make use of block level scoping and classes and other stuff that comes with es6. Migrated [lib/net.js](https://github.com/qeesung/rocketchat-node/pull/25/files#diff-e6ef024c3775d787c38487a6309e491d) as an example :)

**Comment by MatthiasKainer** [comment]
implemented sort, fields and query as well. @graywolf336 can u check if I caught the description correctly in pr https://github.com/qeesung/rocketchat-node/pull/25 pls? Tests are green

**Comment by MatthiasKainer** [comment]
for channels is on master. other *.list interfaces will be added iteratively while we implement them for the v1 api. 

thx @graywolf336 for the info :)
