### ISSUE TITLE
deploy to npm

### ISSUE THREAD

**Issue by MatthiasKainer** [qeesung/rocketchat-node#31]
We need that: https://docs.travis-ci.com/user/deployment/npm/ :D

**Comment by MatthiasKainer** [comment]
@qeesung can you travis setup npm the repository to implement qeesung/rocketchat-node#31? I have no permissions for your travis-ci project. And we are kind of behind-the-master in npm releases ^^

**Comment by qeesung** [comment]
@MatthiasKainer shall we  release rocket chat package to npmjs.org now?  Some features are not supported yet

**Comment by MatthiasKainer** [comment]
true, but the current npm version does not work with current rocketchats at all, and the methods from the old package are fully replaced. Therefore I'd think it would improve the current situation.

**Comment by qeesung** [comment]
Sure, I will setup it .

**Comment by qeesung** [comment]
Resolved by pull requests #50
