### ISSUE TITLE
update username fails with newest version of rocket.chat

### ISSUE THREAD

**Issue by MatthiasKainer** [qeesung/rocketchat-node#41]
update user
      1) updated username should equal to new name

``` 
Uncaught AssertionError: expected RequestError {
  name: 'RequestError',
  statusCode: 400,
  message: 'Meteor.userId can only be invoked in method calls. Use this.userId in publish functions.'
}
```

**Comment by MatthiasKainer** [comment]
Opened bug here: https://github.com/RocketChat/Rocket.Chat/issues/6787

**Comment by qeesung** [comment]
Okay, Need to fix this issue before merge these two pull requests

**Comment by MatthiasKainer** [comment]
Depending on what's the progress on the bug, yes. If this takes too long I'd pin the docker version to 0.55.0 until this is fixed to avoid having only red builds in the future

**Comment by qeesung** [comment]
Maybe now we can locked the docker image version to 0.55.0 before the  issue RocketChat/Rocket.Chat#6787 is resolved

**Comment by qeesung** [comment]
Already locked the docker rocketchat image version to 0.54 with pull request #42

**Comment by MatthiasKainer** [comment]
cool, already re-triggered travis builds

maybe we could offer our api tests as integration tests as a service for the rocket-chat api? Guess most changes breaking the api happen somewhere upstream, so this would help the API development of rocket as quality gate and us because we'd be notified of breaking changes earlier. Does require a strong commitment on test maintenance on our end though

**Comment by qeesung** [comment]
It is a great idea, but how can we offer our api tests as integration for the rocket-chat api?

**Comment by MatthiasKainer** [comment]
by `npm i rocketchat && . node_modules/rocketchat-node/test/setup-testenv.sh && mocha "node_modules/rocketchat-node/test/**/*.test.js"` (prototyped on a mobile phone in a train, might not work ^^)

**Comment by MatthiasKainer** [comment]
Will be fixed with version 0.56.0

**Comment by MatthiasKainer** [comment]
0.56.0 has been released. I'll open a pr with an untagged docker image for the tests

**Comment by MatthiasKainer** [comment]
There has been a breaking change in set user avatar. Will fix this as well. 

Maybe we should sync our versions with the version of rocketchat we have developed against? I.e. call the next release 0.56?

**Comment by qeesung** [comment]
Sure. It is better to understand. should we change both git tag version and package.json version ?

**Comment by MatthiasKainer** [comment]
sry, seems I have overlook this comment - yeah, I think being consistent here would make it easier :)

**Comment by MatthiasKainer** [comment]
I adjusted it in the branch for this release. #64 is already up to date with #68, so if we merge #68 first and #64 second no additional work is needed
