### ISSUE TITLE
Un-x tests for IM

### ISSUE THREAD

**Issue by MatthiasKainer** [qeesung/rocketchat-node#58]

**Comment by qeesung** [comment]
It seems that there is no way to create a direct message room.

**Comment by MatthiasKainer** [comment]
I'll check. Maybe one can do a `rocketChatClient.chat.postMessage({ roomName : "@userForIm", text : message }, callback);` and the im-chat would be automagically there? At least if wiresharking the connection of the app/browser I don't see anything that would trigger a create for IM

**Comment by MatthiasKainer** [comment]
Tested it. The syntax is `rocketChatClient.chat.postMessage({ channel : "@uniqueusername14926023381722", text : "works!"})`, this will return the `rid` in the `message` element of the response object.

**Comment by qeesung** [comment]
fixed by mr #63
