### ISSUE TITLE
Can not subscribe Stream-Room-Messages

### ISSUE THREAD

**Issue by joe223** [qeesung/rocketchat-node#60]
I found there is no `stream-room-messages`, so I use the same way, but can't subscribe `stream-room-messages`. Is there something wrong with my code ? :)
[https://rocket.chat/docs/developer-guides/realtime-api/subscriptions/stream-room-messages](https://rocket.chat/docs/developer-guides/realtime-api/subscriptions/stream-room-messages)
```
import DDP from 'ddp.js';
const endpoint = decodeURIComponent('wss://hmmmmmm.com/websocket');
const ddpOptions = {
    endpoint: endpoint,
    SocketConstructor: WebSocket
};
const ddp = new DDP(ddpOptions);

ddp.sub('stream-room-messages', ['aobEdbYhXfu5hkeqG', false]);

ddp.on('stream-room-messages', message => {
    console.log(message);
});
```

**Comment by MatthiasKainer** [comment]
hejhej @joe223,

I'll look into it. Will have to write a test for it to make sure it works, and take the chance to implement it in the library and tell you what I did afterwards :)

Thx for opening the issue,
M :)

**Comment by MatthiasKainer** [comment]
First thing that seems to be missing in your case btw is authentication. You will have to send method [method/login](https://rocket.chat/docs/developer-guides/realtime-api/method-calls/login) to be able to subscribe to any streams

**Comment by MatthiasKainer** [comment]
@joe223 can you give me a hint in what situation the subscription is supposed to be fired? trying to write a test, but fishing in the dark on what action to perform.

**Comment by MatthiasKainer** [comment]
kk,  got it working. you are simply missing authentication. Rest should work fine. Opened #61 when this passes and closes, a new alpha will be available so you can use the function using our library if you wish :)

**Comment by joe223** [comment]
@MatthiasKainer thx so much. Waiting for the newest version 😁

This is what I wanna do.
Frist of all, get user login with another domain, the url is `127.0.0.1:8080` (Mmmm, I run server in my own PC)
```javasciprt
this.$http.post('https://hmmmmm.com/api/v1/login', {
    username: 'username',
    password: 'password'
}, {
    headers: {
        'Access-Control-Allow-Origin': '*',
    }
}).then(res => {
    res.json();
    user.authToken = data.data.authToken;
    user.userId = data.data.userId;
    // if everything is right,
    // then subscrible the 'stream-room-messages' with the oldest code show before
}, err => {
    // TODO
});
```
`user` and `msg` is already defined when login is successful,
So, I try to send a message
```javascript
this.$http.post('https://hmmmmm.com/api/v1/chat.postMessage', {
    roomId: user.roomId,
    text: msg,
}, {
    headers: {
        'X-Auth-Token': user.authToken,
        'X-User-Id': user.userId,
    }
}).then(res => {
   // can I make 'stream-room-messages' get fired?
}, err => {
    console.error(err);
});
```
Btw, sorry for my terrible English

**Comment by joe223** [comment]
ohh, I got it.
Just forgot the `authentication` , use this code before run `ddp.method('stream-notify-room', ['roomId', false]);`

```javasciprt
ddp.method('login', [
    {
        user: { 'username': 'username' },
        password: 'password'
    }]}
);
ddp.on('changed', (data) => {
    console.log(data);
});
```
`stream-room-messages` will not be fired, but `ddp.on('changed', () => {});`is all right

**Comment by MatthiasKainer** [comment]
To have the stream-room-messages fired, a message has to be posted - see a full working example here [notifyUser.test.js#L75](https://github.com/qeesung/rocketchat-node/blob/master/test/notifyUser.test.js#L75). I'll close the issue as fixed :)
