### ISSUE TITLE
[Feature Request] Lookup user by username

### ISSUE THREAD

**Issue by tim-soft** [qeesung/rocketchat-node#66]
(I believe) that rocketChatClient.users.info() can only accept an id as an argument. 

Is there a way to lookup a user by username? If not, then I'd like to put in an 'ask' to accept an object as an argument with either {id: "12341234"} or {username: "coolDoodName"}

Also, do you accept PR's? Thank you!

**Comment by qeesung** [comment]
Sure, I checked the rocketchat api document [https://rocket.chat/docs/developer-guides/rest-api/users/info](https://rocket.chat/docs/developer-guides/rest-api/users/info), API `/api/v1/users.info` can be called with username, I will update the lib later 😃

**Comment by qeesung** [comment]
@tim-soft fixed the issue. pls update to version `0.2.2-alpha `

**Comment by tim-soft** [comment]
You are awesome! Thank you
