### ISSUE TITLE
Support of subpaths

### ISSUE THREAD

**Issue by mrik974** [qeesung/rocketchat-node#70]
Hi

I have a Rocket.Chat instance running on https://my.domain.com/
I am developing an interface around it and I'm using your library for this.
Because of other needs, I had to move Rocket.Chat to another URL, with a subpath,  https://my.domain.com/rocketchat (doing this by launching Rocketchat with the `
ROOT_URL` env var set to `https://my.domain.com/rocketchat` )

I can't find a way to tell this library to use the specified subpath. Am I missing something?

**Comment by MatthiasKainer** [comment]
Hejhej,
There is currently no way. I'll look into it and implement a solution for you
Best,
m :)

**Comment by MatthiasKainer** [comment]
@mrik974 started pr, with this you can use the client like this:

```js
const config = {
    protocol: "https",
    host: "my.domain.com",
    port: "443",
    username: "user",
    password: "123456",
    basepath: "rocketchat"
};

rocketChatClient = new RocketChatClient(config);
```

There is no specific integration test for this scenario, so basically I'm guessing that it should work. Can you pull the branch and test it pls?

**Comment by mrik974** [comment]
I tested it (just launched a login command) and it works. 
I also had a look at the PR and noticed @qeesung concerns about trailing slashes, so I tested it with both `rocketchat` and `rocketchat/` as basepaths. Both work well
Thank you @MatthiasKainer !

**Comment by MatthiasKainer** [comment]
kk, thx. I'll close this issue as soon as we have a release for that :)

thx for bringing in the topic

**Comment by qeesung** [comment]
@mrik974 new version `0.57.3-alpha` has been released. Please update your version to `0.57.3-alpha`
