### ISSUE TITLE
Broken for current version of rocket.chat

### ISSUE THREAD

**Issue by MatthiasKainer** [qeesung/rocketchat-node#8]
hejhej,

This seems to be broken for current versions of rocket.chat, and uses outdated resources. I.e. for sending instead of the options beeing 

```
        var options = {
            uri: self.makeUri('rooms/'+roomId+"/send"),
            method: 'POST',
            headers:{
                'Content-Type': 'application/json'
            },
            form:{msg:message}
        };
```

it should be more like 

```
        var url = this.makeUri('v1/chat.postMessage');
        var options = {
            uri: url,
            method: 'POST',
            headers:{
                'Accept': 'application/json',
                'Content-Type': 'application/json'
            },
            form:{
                "roomId" : roomId,
                "text" : message
            }
        };
```

Tested only sending, but I guess that's true for every endpoint. Will try to help with merge request, and use this issue to reference the progress if that's okay

Best,
M

**Comment by MatthiasKainer** [comment]
@qeesung at https://github.com/MatthiasKainer/rocketchat-node/commit/4bb067c2ff9231e7decacb248097a7ea5791c17d you can see an example implementation on how the change to the new api may work, in https://github.com/MatthiasKainer/rocketchat-node/commit/fc5bf7e1341ff712f74898a9902449e5a333dccb you can see the implementation. 

Does that looks right to you, or do you have other ideas? Would allow parallel operation independent of the current rocket.chat version, and only newbies who want to use the new version would be required to specify the version. Also, each method is testable with what is expected without integration needs (and have to run multiple versions of rocket.chat)

**Comment by qeesung** [comment]
fixed by pull request  https://github.com/qeesung/rocketchat-node/pull/9

**Comment by MatthiasKainer** [comment]
cool, thx for merging! :+1: 

Already removed the alternative npm package from registry. Do you plan to auto-ci/cd to npm? I'm using this lib in one of our internal tooling (chatbot) and plan to migrate all functions over time, as well as add some more functions (like I already did with the setTopic, which I forgot to document... pr  coming soon). A fast integration would be nice for such. 

Best and thx,
m :)

**Comment by qeesung** [comment]
@MatthiasKainer Yes, I am setting up the travis ci configuration files to run unit test and publish to npm automaticlly

**Comment by qeesung** [comment]
@MatthiasKainer I checked the rocket-chat offical website, compared to the alpha version, the  REST API adds many new interfaces. Then I will add support for the new interface

**Comment by MatthiasKainer** [comment]
@qeesung can help you with that if you like - just create issues for interfaces and assign them to me, so we can split work :)

**Comment by qeesung** [comment]
@MatthiasKainer Oh! It is my pleasure to cooperate with you. And I create some sub tasks at https://github.com/qeesung/rocketchat-node/projects/1.

**Comment by MatthiasKainer** [comment]
@qeesung can you add me as collaborator? Only then can I work on project-tasks (i think - anyways, currently I can't edit or assign anything :D )

**Comment by qeesung** [comment]
@MatthiasKainer Ok. already add you as collaborator. Please check.
